export const sampleDigest = {
  edition: "Wednesday, August 26, 2026",
  title: "Kimwolf fallout and a Kotlin release",
  readingTime: "12 min read",
  introduction: "A security incident is still unfolding while Kotlin quietly changes the shape of everyday Android and server-side work. Today’s digest puts both stories on the same timeline, so the immediate signal has somewhere to land.",
  mustKnow: [
    {
      rank: 1,
      title: "Kimwolf turns a familiar botnet playbook into a wider scan",
      category: "Security",
      score: "9.6 / 10",
      summary: "Researchers are tracking a new wave of Kimwolf activity that combines old credential theft techniques with a faster search across exposed developer infrastructure.",
      background: "The campaign follows a pattern seen in earlier botnets: find a narrow opening, automate the next step, and keep the infrastructure disposable. What makes this wave notable is how quickly it moves from a public scan to a targeted payload.",
      changedOne: "New scans are checking hosted development panels as well as consumer routers.",
      changedTwo: "The latest payload rotates its command endpoint more often, making blocklists less useful.",
      changedThree: "Several affected teams reported the activity before vendor alerts were published.",
      mattersOne: "Security teams need to treat build and observability tools as production attack surfaces.",
      mattersTwo: "Fast-moving infrastructure makes incident timelines more important than a single indicator.",
      unknownOne: "The full victim count is not yet verified across regions.",
      unknownTwo: "It is still unclear whether the operators are selling access or using it directly.",
      timeline: {
        firstDate: "2026-01-02",
        firstEvent: "Kimwolf botnet activity was first documented in a narrow regional scan.",
        secondDate: "2026-01-15",
        secondEvent: "A second wave began probing exposed developer and monitoring panels.",
        thirdDate: "2026-02-03",
        thirdEvent: "The first patch guidance focused on credential rotation and endpoint isolation.",
      },
      sources: {
        firstName: "Krebs on Security",
        firstUrl: "https://krebsonsecurity.com/",
        secondName: "Ars Technica",
        secondUrl: "https://arstechnica.com/",
      },
    },
    {
      rank: 2,
      title: "Kotlin 2.2 makes the compiler feel more like a platform",
      category: "Developer tools",
      score: "8.8 / 10",
      summary: "The release folds more of the language toolchain into a predictable build path, with changes aimed at teams sharing code across Android, server, and desktop targets.",
      background: "Kotlin has spent years turning a popular Android language into a broader application platform. Each release has narrowed the gap between a language feature and the tools required to make that feature safe in a large repository.",
      changedOne: "The compiler pipeline is more consistent across supported targets.",
      changedTwo: "Build diagnostics now point more clearly to the source of a slow or incompatible step.",
      changedThree: "The release notes call out smoother migration paths for multiplatform projects.",
      mattersOne: "Teams can spend less time maintaining target-specific build exceptions.",
      mattersTwo: "A steadier compiler matters when one codebase has to serve several product surfaces.",
      timeline: {
        firstDate: "2025-09-18",
        firstEvent: "Kotlin Multiplatform moved another set of libraries into stable support.",
        secondDate: "2026-03-11",
        secondEvent: "The compiler roadmap shifted toward a unified pipeline for more targets.",
        thirdDate: "2026-08-26",
        thirdEvent: "Kotlin 2.2 ships the next set of compiler and diagnostics changes.",
      },
      sources: {
        firstName: "Kotlin Blog",
        firstUrl: "https://blog.jetbrains.com/kotlin/",
        secondName: "InfoQ",
        secondUrl: "https://www.infoq.com/",
      },
    },
    {
      rank: 3,
      title: "Platform policy teams are writing rules for agent memory",
      category: "Platforms",
      score: "8.2 / 10",
      summary: "Several platform teams are moving from broad AI usage policies to narrower rules for how long-running agents store, reuse, and expose working context.",
      background: "The first wave of policy focused on generated text and model access. As agents begin to hold credentials, plans, and intermediate results, the more difficult question is no longer what a model can produce but what it is allowed to remember.",
      changedOne: "Internal guidance increasingly separates short-lived task context from durable memory.",
      changedTwo: "Audit requirements now include retrieval events, not only final outputs.",
      mattersOne: "The boundary between product behavior and governance is becoming a systems-design concern.",
      mattersTwo: "Clear retention rules make it easier to explain failures to users and regulators.",
      mattersThree: "Teams that define memory before shipping avoid retrofitting consent later.",
      timeline: {
        firstDate: "2026-02-12",
        firstEvent: "First internal guidance separated prompt context from stored user data.",
        secondDate: "2026-05-04",
        secondEvent: "Agent audit plans began recording retrieval and write events.",
        thirdDate: "2026-08-19",
        thirdEvent: "New platform policies began naming memory retention as a product setting.",
      },
      sources: {
        firstName: "The Verge",
        firstUrl: "https://www.theverge.com/",
        secondName: "MIT Technology Review",
        secondUrl: "https://www.technologyreview.com/",
      },
    },
  ],
  alsoKnow: [
    { rank: 1, title: "Rust tooling adds a smaller path to reproducible builds", category: "Developer tools", score: "7.9", detail: "A group of incremental changes makes it easier to compare build inputs before a release leaves CI." },
    { rank: 2, title: "A browser vendor opens another local model interface", category: "Browsers", score: "7.4", detail: "The proposal keeps model calls close to the browser while leaving permissions visible to the user." },
    { rank: 3, title: "Open hardware groups align on a low-power board format", category: "Hardware", score: "7.1", detail: "The emerging format is less about a single chip and more about making small deployments easier to repeat." },
  ],
};
